development:
  adapter: postgresql
  encoding: unicode
  database: sei_development
  pool: 5
  username: sei
  password: sei

test: &test
  adapter: postgresql
  encoding: unicode
  database: sei_test
  pool: 5
  username: sei
  password: sei

production:
  adapter: postgresql
  encoding: unicode
  database: sei_production
  pool: 5
  username: sei
  password: sei

cucumber:
  <<: *test
